"""crear tabla cupones

Revision ID: a1b2c3d4e5f6
Revises: ca8d1ac23311
Create Date: 2026-09-10 23:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'ca8d1ac23311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('PORCENTAJE', 'MONTO_FIJO', name='tipocupon'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usos_maximos', sa.Integer(), nullable=True),
    sa.Column('usos_actuales', sa.Integer(), nullable=False),
    sa.Column('monto_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'EXPIRADO', 'AGOTADO', name='estadocupon'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_cupones_codigo'), 'cupones', ['codigo'], unique=True)
    op.create_index(op.f('ix_cupones_id'), 'cupones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cupones_id'), table_name='cupones')
    op.drop_index(op.f('ix_cupones_codigo'), table_name='cupones')
    op.drop_table('cupones')
    # ### end Alembic commands ###
