"""initial

Revision ID: ca8d1ac23311
Revises: 
Create Date: 2026-09-05 16:02:42.610488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8d1ac23311'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudades_id'), 'ciudades', ['id'], unique=False)
    op.create_table('colores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo_hex', sa.String(length=7), nullable=True),
    sa.Column('imagen_muestra', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colores_id'), 'colores', ['id'], unique=False)
    op.create_table('indicadores_kpi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('valor_actual', sa.Float(), nullable=True),
    sa.Column('valor_objetivo', sa.Float(), nullable=True),
    sa.Column('tendencia', sa.String(length=20), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('ultimo_actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicadores_kpi_id'), 'indicadores_kpi', ['id'], unique=False)
    op.create_table('pasarelas_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('configuracion', sa.JSON(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'MANTENIMIENTO', name='estadopasarela'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasarelas_pago_id'), 'pasarelas_pago', ['id'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tallas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tallas_id'), 'tallas', ['id'], unique=False)
    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporadas_id'), 'temporadas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'BLOQUEADO', name='estadousuario'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_administradores_id'), 'administradores', ['id'], unique=False)
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('modulo', sa.String(length=100), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_id'), 'bitacora', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nit_ci', sa.String(length=20), nullable=False),
    sa.Column('direccion_envio', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit_ci'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('colecciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colecciones_id'), 'colecciones', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagenes', sa.JSON(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'AGOTADO', 'PROXIMO_INGRESO', name='estadoproducto'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('temporada_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=True)
    op.create_table('roles_permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_permisos_id'), 'roles_permisos', ['id'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('horario_atencion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estadosucursal'), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_roles_id'), 'usuarios_roles', ['id'], unique=False)
    op.create_table('cajeros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cajeros_id'), 'cajeros', ['id'], unique=False)
    op.create_table('carritos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'ABANDONADO', 'CONVERTIDO', name='estadocarrito'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carritos_id'), 'carritos', ['id'], unique=False)
    op.create_table('encargados_sucursal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encargados_sucursal_id'), 'encargados_sucursal', ['id'], unique=False)
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_orden', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo', sa.Enum('DIGITAL', 'PRESENCIAL', 'RESERVA', name='tipoorden'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE_PAGO', 'PAGADO', 'EN_PROCESO', 'ENVIADO', 'ENTREGADO', 'CANCELADO', name='estadoorden'), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuentos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('direccion_envio', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_id'), 'ordenes', ['id'], unique=False)
    op.create_index(op.f('ix_ordenes_numero_orden'), 'ordenes', ['numero_orden'], unique=True)
    op.create_table('productos_colecciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('coleccion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_colecciones_id'), 'productos_colecciones', ['id'], unique=False)
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('VENTAS', 'INVENTARIO', 'RESERVAS', 'CLIENTES', 'FINANCIERO', name='tiporeporte'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('formato', sa.Enum('PDF', 'EXCEL', 'CSV', 'JSON', name='formatoreporte'), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administradores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_id'), 'reportes', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_reserva', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_reserva', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horario_aproximado', sa.Time(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PREPARADA', 'EN_PRUEBA', 'COMPLETADA', 'CANCELADA', 'CADUCADA', name='estadoreserva'), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_index(op.f('ix_reservas_numero_reserva'), 'reservas', ['numero_reserva'], unique=True)
    op.create_table('variantes_producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('talla_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('sku_variante', sa.String(length=50), nullable=False),
    sa.Column('precio_variante', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talla_id'], ['tallas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_variante')
    )
    op.create_index(op.f('ix_variantes_producto_id'), 'variantes_producto', ['id'], unique=False)
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('FACTURA', 'RECIBO', 'TICKET', 'NOTA_VENTA', name='tipocomprobante'), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('archivo_pdf', sa.String(length=500), nullable=True),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_comprobantes_id'), 'comprobantes', ['id'], unique=False)
    op.create_table('detalles_orden',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('variante_producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_producto_id'], ['variantes_producto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_orden_id'), 'detalles_orden', ['id'], unique=False)
    op.create_table('detalles_reserva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('variante_producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PREPARADO', 'EN_PRUEBA', 'COMPRADO', 'DEVUELTO', name='estadodetallereserva'), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_producto_id'], ['variantes_producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_reserva_id'), 'detalles_reserva', ['id'], unique=False)
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variante_producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('cantidad_reservada', sa.Integer(), nullable=True),
    sa.Column('cantidad_vendida', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'RESERVADO', 'VENDIDO', 'AGOTADO', 'PROXIMO_A_INGRESAR', name='estadostock'), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_producto_id'], ['variantes_producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_id'), 'inventario', ['id'], unique=False)
    op.create_table('items_carrito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('variante_producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_producto_id'], ['variantes_producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_carrito_id'), 'items_carrito', ['id'], unique=False)
    op.create_table('transacciones_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('pasarela_pago_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('metodo_pago', sa.Enum('TARJETA_DEBITO', 'TARJETA_CREDITO', 'PAYPAL', 'STRIPE', 'QR', 'TRANSFERENCIA', name='metodopagodigital'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'RECHAZADO', 'REEMBOLSADO', 'EN_PROCESO', name='estadotransaccion'), nullable=True),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datos_respuesta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pasarela_pago_id'], ['pasarelas_pago.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_pago_id'), 'transacciones_pago', ['id'], unique=False)
    op.create_table('ventas_presenciales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('cajero_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA_DEBITO', 'TARJETA_CREDITO', 'QR', name='metodopagopresencial'), nullable=False),
    sa.ForeignKeyConstraint(['cajero_id'], ['cajeros.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_presenciales_id'), 'ventas_presenciales', ['id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('RECEPCION', 'VENTA', 'RESERVA', 'DEVOLUCION', 'AJUSTE', 'CANCELACION_RESERVA', name='tipomovimiento'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_id'), 'movimientos_inventario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_inventario_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_ventas_presenciales_id'), table_name='ventas_presenciales')
    op.drop_table('ventas_presenciales')
    op.drop_index(op.f('ix_transacciones_pago_id'), table_name='transacciones_pago')
    op.drop_table('transacciones_pago')
    op.drop_index(op.f('ix_items_carrito_id'), table_name='items_carrito')
    op.drop_table('items_carrito')
    op.drop_index(op.f('ix_inventario_id'), table_name='inventario')
    op.drop_table('inventario')
    op.drop_index(op.f('ix_detalles_reserva_id'), table_name='detalles_reserva')
    op.drop_table('detalles_reserva')
    op.drop_index(op.f('ix_detalles_orden_id'), table_name='detalles_orden')
    op.drop_table('detalles_orden')
    op.drop_index(op.f('ix_comprobantes_id'), table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_index(op.f('ix_variantes_producto_id'), table_name='variantes_producto')
    op.drop_table('variantes_producto')
    op.drop_index(op.f('ix_reservas_numero_reserva'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_reportes_id'), table_name='reportes')
    op.drop_table('reportes')
    op.drop_index(op.f('ix_productos_colecciones_id'), table_name='productos_colecciones')
    op.drop_table('productos_colecciones')
    op.drop_index(op.f('ix_ordenes_numero_orden'), table_name='ordenes')
    op.drop_index(op.f('ix_ordenes_id'), table_name='ordenes')
    op.drop_table('ordenes')
    op.drop_index(op.f('ix_encargados_sucursal_id'), table_name='encargados_sucursal')
    op.drop_table('encargados_sucursal')
    op.drop_index(op.f('ix_carritos_id'), table_name='carritos')
    op.drop_table('carritos')
    op.drop_index(op.f('ix_cajeros_id'), table_name='cajeros')
    op.drop_table('cajeros')
    op.drop_index(op.f('ix_usuarios_roles_id'), table_name='usuarios_roles')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_roles_permisos_id'), table_name='roles_permisos')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_colecciones_id'), table_name='colecciones')
    op.drop_table('colecciones')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_bitacora_id'), table_name='bitacora')
    op.drop_table('bitacora')
    op.drop_index(op.f('ix_administradores_id'), table_name='administradores')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_temporadas_id'), table_name='temporadas')
    op.drop_table('temporadas')
    op.drop_index(op.f('ix_tallas_id'), table_name='tallas')
    op.drop_table('tallas')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_pasarelas_pago_id'), table_name='pasarelas_pago')
    op.drop_table('pasarelas_pago')
    op.drop_index(op.f('ix_indicadores_kpi_id'), table_name='indicadores_kpi')
    op.drop_table('indicadores_kpi')
    op.drop_index(op.f('ix_colores_id'), table_name='colores')
    op.drop_table('colores')
    op.drop_index(op.f('ix_ciudades_id'), table_name='ciudades')
    op.drop_table('ciudades')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###