"""agregar columnas cupon a carritos y ordenes

Revision ID: e807a90aa1db
Revises: a1b2c3d4e5f6
Create Date: 2026-09-10 18:52:57.663502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e807a90aa1db'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carritos', sa.Column('cupon_id', sa.Integer(), nullable=True))
    op.add_column('carritos', sa.Column('descuento_aplicado', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key('carritos_cupon_id_fkey', 'carritos', 'cupones', ['cupon_id'], ['id'], ondelete='SET NULL')
    op.add_column('ordenes', sa.Column('cupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key('ordenes_cupon_id_fkey', 'ordenes', 'cupones', ['cupon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordenes_cupon_id_fkey', 'ordenes', type_='foreignkey')
    op.drop_column('ordenes', 'cupon_id')
    op.drop_constraint('carritos_cupon_id_fkey', 'carritos', type_='foreignkey')
    op.drop_column('carritos', 'descuento_aplicado')
    op.drop_column('carritos', 'cupon_id')
    # ### end Alembic commands ###