"""make_talla_nullable_in_variantes

Revision ID: f3894f381e68
Revises: e807a90aa1db
Create Date: 2026-09-11 10:34:26.286218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3894f381e68'
down_revision: Union[str, None] = 'e807a90aa1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variantes_producto', 'talla_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('variantes_producto_talla_id_fkey', 'variantes_producto', type_='foreignkey')
    op.create_foreign_key(None, 'variantes_producto', 'tallas', ['talla_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variantes_producto', type_='foreignkey')
    op.create_foreign_key('variantes_producto_talla_id_fkey', 'variantes_producto', 'tallas', ['talla_id'], ['id'], ondelete='CASCADE')
    op.alter_column('variantes_producto', 'talla_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###